// <auto-generated />
namespace ProyectoAutos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_AUTOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_AUTOS));
        
        string IMigrationMetadata.Id
        {
            get { return "201604150504236_DB_AUTOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
